"use client"

import React, { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { Badge } from '@/components/ui/badge'
import { Search, FileText, Download, Globe, Brain, CheckCircle2 } from 'lucide-react'
import { toast } from 'sonner'

interface ResearchSource {
  url: string
  title: string
  content: string
  timestamp: number
}

interface DeepResearchProps {
  onArtifactSelect?: (artifact: { content: string; format: 'pdf' | 'md' }) => void
  className?: string
}

export function DeepResearch({ onArtifactSelect, className }: DeepResearchProps) {
  const [query, setQuery] = useState('')
  const [sources, setSources] = useState<ResearchSource[]>([])
  const [isResearching, setIsResearching] = useState(false)
  const [progress, setProgress] = useState(0)
  const [currentStep, setCurrentStep] = useState('')
  const [analysis, setAnalysis] = useState('')

  const startResearch = async () => {
    if (!query.trim()) {
      toast.error('Please enter a research topic')
      return
    }

    setIsResearching(true)
    setProgress(0)
    setSources([])
    setAnalysis('')
    setCurrentStep('Searching for relevant sources...')

    try {
      // Simulate research process (in production, this would use real web browsing)
      await simulateResearch()
      
      // Generate analysis
      setCurrentStep('Generating analysis...')
      setProgress(80)
      
      const analysisText = generateAnalysis(query, sources)
      setAnalysis(analysisText)
      
      setProgress(100)
      setCurrentStep('Research completed!')
      toast.success('Deep research completed successfully!')
    } catch (error: any) {
      console.error('Research error:', error)
      toast.error('Research failed. Please try again.')
    } finally {
      setIsResearching(false)
    }
  }

  const simulateResearch = async () => {
    // Simulate finding sources
    setCurrentStep('Searching web for relevant sources...')
    setProgress(20)
    await new Promise(resolve => setTimeout(resolve, 1000))

    // Simulate fetching content
    setCurrentStep('Fetching content from sources...')
    setProgress(40)
    await new Promise(resolve => setTimeout(resolve, 1000))

    // Add mock sources
    const mockSources: ResearchSource[] = [
      {
        url: 'https://example.com/article1',
        title: `${query} - Overview and Analysis`,
        content: `This article provides a comprehensive overview of ${query}, covering key concepts, recent developments, and practical applications...`,
        timestamp: Date.now()
      },
      {
        url: 'https://example.com/article2',
        title: `Understanding ${query} in Depth`,
        content: `A deep dive into ${query} with technical details, implementation strategies, and best practices...`,
        timestamp: Date.now()
      },
      {
        url: 'https://example.com/article3',
        title: `${query} Best Practices Guide`,
        content: `Essential best practices for working with ${query}, including common pitfalls and optimization techniques...`,
        timestamp: Date.now()
      }
    ]

    setSources(mockSources)
    setCurrentStep('Analyzing gathered information...')
    setProgress(60)
    await new Promise(resolve => setTimeout(resolve, 1000))
  }

  const generateAnalysis = (topic: string, sourcesList: ResearchSource[]): string => {
    return `# Deep Research Analysis: ${topic}

## Executive Summary
This report provides a comprehensive analysis of ${topic} based on research from ${sourcesList.length} authoritative sources.

## Key Findings
- **Primary Insight**: ${topic} represents a significant area of interest with broad applications
- **Current State**: The field is rapidly evolving with new developments emerging regularly
- **Future Outlook**: Strong growth potential with increasing adoption across industries

## Detailed Analysis

### Source 1: ${sourcesList[0]?.title || 'Overview'}
${sourcesList[0]?.content || 'No content available'}

### Source 2: ${sourcesList[1]?.title || 'Technical Details'}
${sourcesList[1]?.content || 'No content available'}

### Source 3: ${sourcesList[2]?.title || 'Best Practices'}
${sourcesList[2]?.content || 'No content available'}

## Recommendations
1. Implement ${topic} gradually with proper testing
2. Monitor industry developments and best practices
3. Consider scalability and performance requirements
4. Ensure proper documentation and knowledge transfer

## Conclusion
${topic} offers significant opportunities for innovation and improvement. Organizations should consider strategic adoption while maintaining awareness of implementation challenges.

---
*Generated by Aether AI Deep Research Mode*
*Generated: ${new Date().toLocaleString()}*
`
  }

  const downloadArtifact = (format: 'pdf' | 'md') => {
    if (!analysis) {
      toast.error('No analysis available to download')
      return
    }

    const artifact = {
      content: analysis,
      format
    }

    if (onArtifactSelect) {
      onArtifactSelect(artifact)
      toast.success(`Analysis selected as ${format.toUpperCase()} artifact`)
    }
  }

  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Brain className="w-5 h-5" />
          Deep Research Mode
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex gap-2">
          <Input
            placeholder="Enter research topic (e.g., 'React performance optimization')"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && startResearch()}
            className="flex-1"
          />
          <Button 
            onClick={startResearch} 
            disabled={!query.trim() || isResearching}
            size="sm"
          >
            <Search className="w-4 h-4 mr-1" />
            Research
          </Button>
        </div>

        {isResearching && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium">{currentStep}</span>
              <span className="text-sm text-muted-foreground">{progress}%</span>
            </div>
            <Progress value={progress} className="h-2" />
          </div>
        )}

        {sources.length > 0 && (
          <div className="space-y-3">
            <h4 className="text-sm font-medium">Research Sources</h4>
            <div className="space-y-2">
              {sources.map((source, idx) => (
                <div key={idx} className="p-3 bg-gray-50 rounded-lg">
                  <div className="flex items-center gap-2 mb-1">
                    <Globe className="w-3 h-3" />
                    <span className="text-xs font-medium">{source.title}</span>
                  </div>
                  <p className="text-xs text-muted-foreground truncate">{source.content}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {analysis && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="text-sm font-medium flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-green-500" />
                Analysis Complete
              </h4>
              <Badge variant="outline">Markdown</Badge>
            </div>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={() => downloadArtifact('md')}
              >
                <FileText className="w-3 h-3 mr-1" />
                Export MD
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => downloadArtifact('pdf')}
              >
                <Download className="w-3 h-3 mr-1" />
                Export PDF
              </Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
